import path from "node:path";
import { randomUUID } from "node:crypto";
// path used for brief/workspace resolution
import {
  loadDotEnv,
  loadExecutors,
  loadOrchestratorConfig,
  repoRoot,
} from "./config.js";
import { MockExecutor, ensureWorktree } from "./adapters/mock.js";
import { OpenCodeHttpExecutor } from "./adapters/opencode-http.js";
import {
  findActiveRun,
  latestRun,
  newRunId,
  readState,
  readText,
  writeBrief,
  writeState,
} from "./state.js";
import type { ExecutorAdapter, RunState } from "./types.js";
import {
  getUserTargetWorkspace,
  resolveTargetWorkspace,
  setUserTargetWorkspace,
} from "./workspace.js";

loadDotEnv();

function getAdapter(type: string): ExecutorAdapter {
  if (type === "mock") return new MockExecutor();
  if (type === "opencode-http") return new OpenCodeHttpExecutor();
  throw new Error(`Unknown executor type: ${type}`);
}

function resolveExecutorId(override?: string): string {
  const cfg = loadOrchestratorConfig();
  return (
    override ||
    process.env.ORCHESTRATOR_EXECUTOR ||
    cfg.default_executor ||
    "mock"
  );
}

function buildBriefFromPlan(
  plan: string,
  extra: string | undefined,
  workspaceAbs: string,
): string {
  return [
    "# Execution Brief",
    "",
    "Generated by opencode-bridge for an executor agent.",
    "",
    `## Working directory (MUST use this cwd)`,
    "",
    `\`${workspaceAbs}\``,
    "",
    "All file edits, builds, and tests happen **only** under this directory unless the plan says otherwise.",
    "",
    "## Plan (source of truth)",
    "",
    plan.trim(),
    "",
    extra?.trim() ? `## Additional instructions\n\n${extra.trim()}\n` : "",
    "## Reporting",
    "",
    "- Stay in scope",
    "- Do not push git remotes",
    "- Destructive commands require human confirmation (orchestrator gates)",
    "",
  ].join("\n");
}

export async function dispatch(args: {
  planPath?: string;
  executorId?: string;
  confirm?: boolean;
  extraInstructions?: string;
  confirmedToken?: string;
  /** OpenCode 工作目录：绝对路径，或相对编排仓；覆盖默认 target */
  workspace?: string;
}): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const orch = loadOrchestratorConfig(root);
  const execs = loadExecutors(root);
  const planPath = args.planPath || "plans/current.md";
  const plan = readText(planPath, root);
  const executorId = resolveExecutorId(args.executorId);
  const def = execs.executors[executorId];
  if (!def) throw new Error(`Unknown executor id: ${executorId}`);

  const ws = resolveTargetWorkspace({
    dispatchWorkspace: args.workspace,
    planText: plan,
    orchDefault: orch.default_workspace,
    useWorktree: orch.use_worktree,
    root,
  });

  const needConfirm =
    args.confirm !== undefined ? args.confirm : orch.confirm_before_dispatch;

  if (needConfirm && !args.confirmedToken) {
    const id = newRunId();
    const brief = buildBriefFromPlan(plan, args.extraInstructions, ws.absPath);
    const briefPath = writeBrief(id, brief, root);
    const token = randomUUID();
    const state: RunState = {
      id,
      status: "awaiting_confirm",
      executorId,
      executorType: def.type,
      planPath,
      briefPath: path.relative(root, briefPath),
      workspace: ws.label,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      confirmToken: token,
      summary: "Brief ready — re-call dispatch with confirmedToken to start",
    };
    writeState(state, root);
    return {
      ok: true,
      needsConfirm: true,
      runId: id,
      confirmToken: token,
      briefPath: state.briefPath,
      workspace: ws.absPath,
      workspaceSource: ws.source,
      workspaceExternal: ws.isExternal,
      briefPreview: brief.slice(0, 1200),
      message:
        "Review the brief and workspace path. Call dispatch again with confirmedToken to start.",
    };
  }

  let state: RunState | null = null;
  if (args.confirmedToken) {
    const active = findActiveRun(root);
    if (!active || active.confirmToken !== args.confirmedToken) {
      throw new Error("Invalid or missing confirmedToken");
    }
    state = active;
    if (args.workspace) state.workspace = ws.label;
  } else {
    const id = newRunId();
    const brief = buildBriefFromPlan(plan, args.extraInstructions, ws.absPath);
    const briefPath = writeBrief(id, brief, root);
    state = {
      id,
      status: "starting",
      executorId,
      executorType: def.type,
      planPath,
      briefPath: path.relative(root, briefPath),
      workspace: ws.label,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }

  // Re-resolve in case confirm path used older state without abs
  const wsFinal = resolveTargetWorkspace({
    dispatchWorkspace: args.workspace || (path.isAbsolute(state.workspace) ? state.workspace : undefined),
    planText: plan,
    orchDefault: state.workspace || orch.default_workspace,
    useWorktree: orch.use_worktree,
    root,
  });

  let workspaceAbs = wsFinal.absPath;
  const briefFull = buildBriefFromPlan(
    plan,
    args.extraInstructions,
    workspaceAbs,
  );
  writeBrief(state.id, briefFull, root);
  state.briefPath = path.relative(root, path.join(root, "briefs", `${state.id}.md`));
  state.workspace = wsFinal.label;

  if (wsFinal.useWorktree) {
    workspaceAbs = ensureWorktree(
      root,
      state.id,
      path.isAbsolute(wsFinal.label) ? orch.default_workspace : wsFinal.label,
    );
    state.worktreePath = path.join("runs", state.id, "worktree");
  }

  state.status = "starting";
  writeState(state, root);

  const adapter = getAdapter(def.type);
  try {
    const started = await adapter.start({
      run: state,
      brief: briefFull,
      workspace: workspaceAbs,
      options: def.options,
    });
    state.sessionId = started.sessionId;
    state.status = "running";
    state.summary = started.summary;
    writeState(state, root);

    const poll = await adapter.poll({ run: state, options: def.options });
    if (poll.status === "completed") {
      state.status = "completed";
      state.lastProgress = poll.progress;
      state.summary = poll.summary;
      writeState(state, root);
    }

    return {
      ok: true,
      needsConfirm: false,
      runId: state.id,
      status: state.status,
      sessionId: state.sessionId,
      summary: state.summary,
      worktreePath: state.worktreePath,
      workspace: workspaceAbs,
      workspaceSource: wsFinal.source,
      workspaceExternal: wsFinal.isExternal,
    };
  } catch (e) {
    state.status = "failed";
    state.error = e instanceof Error ? e.message : String(e);
    writeState(state, root);
    throw e;
  }
}

export async function setWorkspaceTool(workspacePath: string) {
  return setUserTargetWorkspace(workspacePath);
}

export async function getWorkspaceTool() {
  const root = repoRoot();
  const orch = loadOrchestratorConfig(root);
  const user = getUserTargetWorkspace();
  try {
    const resolved = resolveTargetWorkspace({
      orchDefault: orch.default_workspace,
      useWorktree: orch.use_worktree,
      root,
    });
    return {
      ok: true,
      orchestratorRoot: root,
      targetWorkspace: resolved.absPath,
      source: resolved.source,
      external: resolved.isExternal,
      useWorktree: resolved.useWorktree,
      userConfigPath: user.configPath,
      envOverride: user.env,
      hint: "Codex 打开编排仓用 Skills；OpenCode 在 targetWorkspace 里改代码/build",
    };
  } catch (e) {
    return {
      ok: false,
      orchestratorRoot: root,
      error: e instanceof Error ? e.message : String(e),
      userConfigPath: user.configPath,
    };
  }
}

export async function status(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = runId ? readState(runId, root) : findActiveRun(root) || latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const poll = await adapter.poll({
    run: state,
    options: def?.options || {},
  });
  if (state.status === "running" || state.status === "starting") {
    state.status = poll.status;
    state.lastProgress = poll.progress;
    state.summary = poll.summary || state.summary;
    writeState(state, root);
  }
  return {
    ok: true,
    run: state,
    poll,
  };
}

export async function interrupt(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = runId ? readState(runId, root) : findActiveRun(root);
  if (!state) return { ok: false, message: "No active run" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const res = await adapter.abort({ run: state, options: def?.options || {} });
  state.status = "interrupted";
  state.summary = res.summary;
  writeState(state, root);
  return { ok: res.ok, run: state };
}

export async function rework(args: {
  runId?: string;
  extraInstructions: string;
  confirm?: boolean;
}): Promise<Record<string, unknown>> {
  await interrupt(args.runId);
  return dispatch({
    extraInstructions: args.extraInstructions,
    confirm: args.confirm ?? false,
    executorId: undefined,
  });
}

export async function progress(args?: {
  runId?: string;
  prompt?: string;
}): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = args?.runId
    ? readState(args.runId, root)
    : findActiveRun(root) || latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const res = await adapter.progress({
    run: state,
    options: def?.options || {},
    prompt: args?.prompt,
  });
  state.lastProgress = res.progress;
  writeState(state, root);
  return { ok: true, runId: state.id, progress: res.progress };
}

export async function reviewContext(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const orch = loadOrchestratorConfig(root);
  const state = runId ? readState(runId, root) : latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const plan = readText(state.planPath, root);
  const brief = readText(state.briefPath, root);
  const st = await status(state.id);
  return {
    ok: true,
    run: state,
    plan,
    brief,
    status: st,
    acceptanceCommands: orch.acceptance?.commands || [],
    gates: orch.gates,
  };
}
