import path from "node:path";
import { randomUUID } from "node:crypto";
// path used for brief/workspace resolution
import {
  loadDotEnv,
  loadExecutors,
  loadOrchestratorConfig,
  repoRoot,
} from "./config.js";
import { MockExecutor, ensureWorktree } from "./adapters/mock.js";
import { OpenCodeHttpExecutor } from "./adapters/opencode-http.js";
import {
  findActiveRun,
  latestRun,
  newRunId,
  readState,
  readText,
  writeBrief,
  writeState,
} from "./state.js";
import type { ExecutorAdapter, RunState } from "./types.js";

loadDotEnv();

function getAdapter(type: string): ExecutorAdapter {
  if (type === "mock") return new MockExecutor();
  if (type === "opencode-http") return new OpenCodeHttpExecutor();
  throw new Error(`Unknown executor type: ${type}`);
}

function resolveExecutorId(override?: string): string {
  const cfg = loadOrchestratorConfig();
  return (
    override ||
    process.env.ORCHESTRATOR_EXECUTOR ||
    cfg.default_executor ||
    "mock"
  );
}

function buildBriefFromPlan(plan: string, extra?: string): string {
  return [
    "# Execution Brief",
    "",
    "Generated by opencode-bridge for an executor agent.",
    "",
    "## Plan (source of truth)",
    "",
    plan.trim(),
    "",
    extra?.trim() ? `## Additional instructions\n\n${extra.trim()}\n` : "",
    "## Reporting",
    "",
    "- Stay in scope",
    "- Do not push git remotes",
    "- Destructive commands require human confirmation (orchestrator gates)",
    "",
  ].join("\n");
}

export async function dispatch(args: {
  planPath?: string;
  executorId?: string;
  confirm?: boolean;
  extraInstructions?: string;
  confirmedToken?: string;
}): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const orch = loadOrchestratorConfig(root);
  const execs = loadExecutors(root);
  const planPath = args.planPath || "plans/current.md";
  const plan = readText(planPath, root);
  const executorId = resolveExecutorId(args.executorId);
  const def = execs.executors[executorId];
  if (!def) throw new Error(`Unknown executor id: ${executorId}`);

  // Confirm flow: first call without confirmedToken returns brief draft
  const needConfirm =
    args.confirm !== undefined ? args.confirm : orch.confirm_before_dispatch;

  if (needConfirm && !args.confirmedToken) {
    const id = newRunId();
    const brief = buildBriefFromPlan(plan, args.extraInstructions);
    const briefPath = writeBrief(id, brief, root);
    const token = randomUUID();
    const state: RunState = {
      id,
      status: "awaiting_confirm",
      executorId,
      executorType: def.type,
      planPath,
      briefPath: path.relative(root, briefPath),
      workspace: orch.default_workspace,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      confirmToken: token,
      summary: "Brief ready — re-call dispatch with confirmedToken to start",
    };
    writeState(state, root);
    return {
      ok: true,
      needsConfirm: true,
      runId: id,
      confirmToken: token,
      briefPath: state.briefPath,
      briefPreview: brief.slice(0, 1200),
      message:
        "Review the brief. Call dispatch again with confirmedToken to start execution.",
    };
  }

  let state: RunState | null = null;
  if (args.confirmedToken) {
    const active = findActiveRun(root);
    if (!active || active.confirmToken !== args.confirmedToken) {
      throw new Error("Invalid or missing confirmedToken");
    }
    state = active;
  } else {
    const id = newRunId();
    const brief = buildBriefFromPlan(plan, args.extraInstructions);
    const briefPath = writeBrief(id, brief, root);
    state = {
      id,
      status: "starting",
      executorId,
      executorType: def.type,
      planPath,
      briefPath: path.relative(root, briefPath),
      workspace: orch.default_workspace,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }

  const briefFull = readText(state.briefPath, root);
  let workspaceAbs = path.join(root, orch.default_workspace);
  if (orch.use_worktree) {
    workspaceAbs = ensureWorktree(root, state.id, orch.default_workspace);
    state.worktreePath = path.relative(root, path.dirname(workspaceAbs)) === "runs"
      ? path.join("runs", state.id, "worktree")
      : path.join("runs", state.id, "worktree");
    // ensureWorktree returns .../worktree/playground
    state.worktreePath = path.join("runs", state.id, "worktree");
  }

  state.status = "starting";
  writeState(state, root);

  const adapter = getAdapter(def.type);
  try {
    const started = await adapter.start({
      run: state,
      brief: briefFull,
      workspace: workspaceAbs,
      options: def.options,
    });
    state.sessionId = started.sessionId;
    state.status = "running";
    state.summary = started.summary;
    writeState(state, root);

    // Mock completes almost immediately — poll once
    const poll = await adapter.poll({ run: state, options: def.options });
    if (poll.status === "completed") {
      state.status = "completed";
      state.lastProgress = poll.progress;
      state.summary = poll.summary;
      writeState(state, root);
    }

    return {
      ok: true,
      needsConfirm: false,
      runId: state.id,
      status: state.status,
      sessionId: state.sessionId,
      summary: state.summary,
      worktreePath: state.worktreePath,
    };
  } catch (e) {
    state.status = "failed";
    state.error = e instanceof Error ? e.message : String(e);
    writeState(state, root);
    throw e;
  }
}

export async function status(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = runId ? readState(runId, root) : findActiveRun(root) || latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const poll = await adapter.poll({
    run: state,
    options: def?.options || {},
  });
  if (state.status === "running" || state.status === "starting") {
    state.status = poll.status;
    state.lastProgress = poll.progress;
    state.summary = poll.summary || state.summary;
    writeState(state, root);
  }
  return {
    ok: true,
    run: state,
    poll,
  };
}

export async function interrupt(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = runId ? readState(runId, root) : findActiveRun(root);
  if (!state) return { ok: false, message: "No active run" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const res = await adapter.abort({ run: state, options: def?.options || {} });
  state.status = "interrupted";
  state.summary = res.summary;
  writeState(state, root);
  return { ok: res.ok, run: state };
}

export async function rework(args: {
  runId?: string;
  extraInstructions: string;
  confirm?: boolean;
}): Promise<Record<string, unknown>> {
  await interrupt(args.runId);
  return dispatch({
    extraInstructions: args.extraInstructions,
    confirm: args.confirm ?? false,
    executorId: undefined,
  });
}

export async function progress(args?: {
  runId?: string;
  prompt?: string;
}): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const execs = loadExecutors(root);
  const state = args?.runId
    ? readState(args.runId, root)
    : findActiveRun(root) || latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const def = execs.executors[state.executorId];
  const adapter = getAdapter(def?.type || state.executorType);
  const res = await adapter.progress({
    run: state,
    options: def?.options || {},
    prompt: args?.prompt,
  });
  state.lastProgress = res.progress;
  writeState(state, root);
  return { ok: true, runId: state.id, progress: res.progress };
}

export async function reviewContext(runId?: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const orch = loadOrchestratorConfig(root);
  const state = runId ? readState(runId, root) : latestRun(root);
  if (!state) return { ok: false, message: "No runs found" };
  const plan = readText(state.planPath, root);
  const brief = readText(state.briefPath, root);
  const st = await status(state.id);
  return {
    ok: true,
    run: state,
    plan,
    brief,
    status: st,
    acceptanceCommands: orch.acceptance?.commands || [],
    gates: orch.gates,
  };
}
