/**
 * API / model profiles: switch provider or model without editing many files.
 * - config/profiles.yaml  — named profiles (model or type: mock)
 * - config/active.local.yaml — current selection (gitignored)
 */
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import { repoRoot } from "./config.js";
import type { ExecutorDef } from "./types.js";

export type ProfileDef = {
  /** OpenCode model id: providerId/modelId */
  model?: string;
  /** Built-in executor type (currently only mock) */
  type?: "mock" | "opencode-http";
  /** Short note for orch use listing */
  note?: string;
};

export type ProfilesFile = {
  /** Default profile when none active */
  default?: string;
  profiles: Record<string, ProfileDef>;
};

export type ResolvedExecutor = {
  id: string;
  def: ExecutorDef;
  profile?: string;
  source: "override" | "env" | "active" | "profiles_default" | "orchestrator_default";
};

function profilesPath(root = repoRoot()): string {
  return path.join(root, "config/profiles.yaml");
}

function activePath(root = repoRoot()): string {
  return path.join(root, "config/active.local.yaml");
}

export function loadProfiles(root = repoRoot()): ProfilesFile {
  const p = profilesPath(root);
  if (!fs.existsSync(p)) return { profiles: {} };
  const raw = yaml.load(fs.readFileSync(p, "utf8")) as ProfilesFile | null;
  return {
    default: raw?.default,
    profiles: raw?.profiles || {},
  };
}

export function readActiveProfileName(root = repoRoot()): string | null {
  const env =
    process.env.ORCHESTRATOR_PROFILE || process.env.ORCHESTRATOR_EXECUTOR;
  if (env?.trim()) return env.trim();

  const p = activePath(root);
  if (!fs.existsSync(p)) return null;
  const raw = yaml.load(fs.readFileSync(p, "utf8")) as {
    active?: string;
    profile?: string;
  } | null;
  const name = raw?.active || raw?.profile;
  return name?.trim() || null;
}

/** Persist selection (does not require the profile to exist yet — validated by callers). */
export function writeActiveProfile(name: string, root = repoRoot()): void {
  const p = activePath(root);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(
    p,
    `# Generated by: orch use ${name}\n# Do not commit (see .gitignore)\nactive: ${name}\n`,
    "utf8",
  );
}

function opencodeHttpDef(model: string): ExecutorDef {
  return {
    type: "opencode-http",
    options: {
      model,
      autoStartServe: true,
    },
  };
}

function mockDef(): ExecutorDef {
  return { type: "mock", options: {} };
}

export function resolveProfileToExecutor(
  profileName: string,
  root = repoRoot(),
): { id: string; def: ExecutorDef } {
  const file = loadProfiles(root);
  const profile = file.profiles[profileName];

  if (profile) {
    if (profile.model?.trim()) {
      return { id: profileName, def: opencodeHttpDef(profile.model.trim()) };
    }
    if (profile.type === "mock" || profileName === "mock") {
      return { id: profileName, def: mockDef() };
    }
    throw new Error(
      `profile "${profileName}" 需要 model: 或 type: mock（config/profiles.yaml）`,
    );
  }

  if (profileName === "mock") {
    return { id: "mock", def: mockDef() };
  }

  const names = Object.keys(file.profiles);
  throw new Error(
    `未知 profile: "${profileName}"。可用: ${names.join(", ") || "(无)"}`,
  );
}

/**
 * Priority: explicit override → ORCHESTRATOR_PROFILE/EXECUTOR → active.local.yaml
 * → profiles.default → orchestrator default_executor → mock
 */
export function resolveExecutor(
  override?: string,
  orchestratorDefault?: string,
  root = repoRoot(),
): ResolvedExecutor {
  const file = loadProfiles(root);

  if (override?.trim()) {
    const r = resolveProfileToExecutor(override.trim(), root);
    return { ...r, profile: override.trim(), source: "override" };
  }

  const env =
    process.env.ORCHESTRATOR_PROFILE?.trim() ||
    process.env.ORCHESTRATOR_EXECUTOR?.trim();
  if (env) {
    const r = resolveProfileToExecutor(env, root);
    return {
      ...r,
      profile: env,
      source: "env",
    };
  }

  const activeFile = activePath(root);
  if (fs.existsSync(activeFile)) {
    const raw = yaml.load(fs.readFileSync(activeFile, "utf8")) as {
      active?: string;
    } | null;
    const name = raw?.active?.trim();
    if (name) {
      const r = resolveProfileToExecutor(name, root);
      return { ...r, profile: name, source: "active" };
    }
  }

  if (file.default?.trim()) {
    const name = file.default.trim();
    const r = resolveProfileToExecutor(name, root);
    return { ...r, profile: name, source: "profiles_default" };
  }

  const fallback = orchestratorDefault?.trim() || "mock";
  const r = resolveProfileToExecutor(fallback, root);
  return {
    ...r,
    profile: fallback,
    source: "orchestrator_default",
  };
}

/** Update root opencode.json top-level "model" so serve default matches profile. */
export function syncOpencodeDefaultModel(
  model: string,
  root = repoRoot(),
): boolean {
  const p = path.join(root, "opencode.json");
  if (!fs.existsSync(p)) return false;
  try {
    const raw = JSON.parse(fs.readFileSync(p, "utf8")) as Record<string, unknown>;
    raw.model = model;
    fs.writeFileSync(p, JSON.stringify(raw, null, 2) + "\n", "utf8");
    return true;
  } catch {
    return false;
  }
}

function providerOfModel(model?: string | null): string | null {
  if (!model || !model.includes("/")) return null;
  return model.split("/")[0];
}

function readActiveFromFile(root = repoRoot()): string | null {
  const p = activePath(root);
  if (!fs.existsSync(p)) return null;
  try {
    const raw = yaml.load(fs.readFileSync(p, "utf8")) as {
      active?: string;
      profile?: string;
    } | null;
    return (raw?.active || raw?.profile || "").trim() || null;
  } catch {
    return null;
  }
}

export function listProfilesTool(): Record<string, unknown> {
  const root = repoRoot();
  const file = loadProfiles(root);
  const resolved = resolveExecutor(undefined, undefined, root);
  return {
    ok: true,
    active: resolved.profile || resolved.id,
    activeExecutorId: resolved.id,
    activeModel: resolved.def.options?.model ?? null,
    source: resolved.source,
    default: file.default ?? null,
    profiles: Object.entries(file.profiles).map(([name, p]) => ({
      name,
      model: p.model ?? null,
      type: p.type ?? (p.model ? "opencode-http" : null),
      note: p.note ?? null,
      provider: providerOfModel(p.model) || null,
      current: name === resolved.profile || name === resolved.id,
    })),
  };
}

/**
 * Switch profile. Same provider + live OpenCode session → keep session, only change model.
 * Different provider → only updates default for next dispatch (cannot keep API context).
 */
export async function useProfileTool(name: string): Promise<Record<string, unknown>> {
  const root = repoRoot();
  const trimmed = name.trim();
  if (!trimmed) {
    return { ok: false, message: "用法: use <profile名>；先 orch use 查看列表" };
  }
  const resolved = resolveProfileToExecutor(trimmed, root);
  const nextModel =
    typeof resolved.def.options?.model === "string"
      ? resolved.def.options.model
      : undefined;
  const nextProvider = providerOfModel(nextModel);

  const prevName = readActiveFromFile(root);
  let prevModel: string | undefined;
  if (prevName) {
    try {
      const prev = resolveProfileToExecutor(prevName, root);
      prevModel =
        typeof prev.def.options?.model === "string"
          ? prev.def.options.model
          : undefined;
    } catch {
      /* ignore */
    }
  }
  const prevProvider = providerOfModel(prevModel);
  const sameProvider = Boolean(
    prevProvider && nextProvider && prevProvider === nextProvider,
  );

  writeActiveProfile(trimmed, root);
  let syncedOpencode = false;
  if (nextModel) syncedOpencode = syncOpencodeDefaultModel(nextModel, root);

  let contextPreserved = false;
  let runId: string | null = null;
  let sessionId: string | null = null;
  let contextNote =
    "已更新默认 profile；新派工将使用该模型。当前若无进行中的 OpenCode 会话，无上下文可保留。";

  if (sameProvider && nextModel && resolved.def.type === "opencode-http") {
    try {
      const { getBoundWorkspace } = await import("./workspace.js");
      const { findActiveRun, latestRun, writeState } = await import("./state.js");
      const { OpenCodeHttpExecutor } = await import("./adapters/opencode-http.js");
      const bound = getBoundWorkspace(root);
      if (bound) {
        const activeStatuses = new Set([
          "awaiting_confirm",
          "starting",
          "running",
          "awaiting_review",
          "stalled",
        ]);
        const run =
          findActiveRun(bound.absPath) ||
          latestRun(bound.absPath);
        if (
          run?.sessionId &&
          activeStatuses.has(run.status) &&
          run.executorType === "opencode-http"
        ) {
          const adapter = new OpenCodeHttpExecutor();
          await adapter.progress({
            run,
            options: resolved.def.options,
            model: nextModel,
            prompt: [
              `Model switch (same provider ${nextProvider}): now using ${nextModel}.`,
              "Keep all prior conversation and task context.",
              "Do NOT restart the task from scratch. Continue from the current step.",
            ].join(" "),
          });
          run.executorId = resolved.id;
          run.model = nextModel;
          run.summary = `Switched model to ${nextModel} (context preserved)`;
          writeState(run, bound.absPath);
          contextPreserved = true;
          runId = run.id;
          sessionId = run.sessionId;
          contextNote =
            "同商家换模型：已在同一 OpenCode 会话继续（上下文保留）。";
        }
      }
    } catch (e) {
      contextNote = `同商家切换已记录，但未能注入进行中会话: ${
        e instanceof Error ? e.message : String(e)
      }`;
    }
  } else if (prevProvider && nextProvider && prevProvider !== nextProvider) {
    contextNote =
      "已换商家：无法保留上一会话的 API 上下文。进行中的 run 仍用旧模型；新派工才走新商家。";
  }

  return {
    ok: true,
    active: trimmed,
    executorId: resolved.id,
    model: nextModel ?? null,
    provider: nextProvider,
    sameProvider,
    contextPreserved,
    runId,
    sessionId,
    syncedOpencode,
    message: nextModel
      ? `已切换到 "${trimmed}"（${nextModel}）。${contextNote}`
      : `已切换到 "${trimmed}"（executor=${resolved.id}）。${contextNote}`,
  };
}
